baseURL = "https://blog.bessas.me/"
title = "That's weird..."
author = "Apostolis Bessas"
canonifyurls = true
languageCode = "en-us"
theme = "hugo-steam-theme"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "That's weird..."
  title = "That's weird..."
  themecolor = "blue"

  name = "Apostolis Bessas"
  bio = ""
  description = ""

  github = "mpessas"
