baseURL = 'https://blog.bessas.me/'
languageCode = 'en-us'
title = "That's weird..."
theme = "paper"
paginate = 10

[author]
  name = 'Apostolis Bessas'

[params]
  # paper theme
  color = 'gray'
  github = 'mpessas'
  rss = true
