baseURL = "https://blog.bessas.me/"
title = "That's weird..."
author = "Apostolis Bessas"
canonifyurls = true
languageCode = "en-us"
theme = "black-and-light"

googleAnalytics = "UA-26208931-1"

pygmentsstyle       = "bw"
pygmentscodefences  = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  sitename = "That's weird..."
  disableWebFonts = true

[[menu.main]]
    name = "Github"
    url  = "https://github.com/mpessas/"
