languageCode = "en-us"
title = "That's weird..."
baseURL = "http://blog.bessas.me/"
theme = "black-and-light"
author = "Apostolos Bessas"
canonifyurls = true

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "That's weird..."

[[menu.main]]
    name = "Github"
    url  = "https://github.com/mpessas/"
