baseURL = 'https://blog.bessas.me/'
languageCode = 'en-us'
title = "That's weird..."
theme = "paper"
paginate = 10
sectionPagesMenu = 'main'

[params]
  # paper theme
  color = 'linen'
  github = 'mpessas'
  linkedin = 'bessas'
  rss = true


[markup.highlight]
style = 'modus-operandi'
